name: CI

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/build-push-action@v6
        with:
          context: .
          target: lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - uses: docker/build-push-action@v6
        with:
          context: .
          target: test

  cd:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: cybercyst/github-actions/.github/workflows/cd.yaml@main
